sudo: required
language:
  - node_js
os: osx
matrix:
  include:
    - osx_image: xcode8.3
      nodejs: "8"
    - osx_image: xcode8.3
      nodejs: "10"

    - osx_image: xcode9.4
      nodejs: "8"
    - osx_image: xcode9.4
      nodejs: "10"

    - osx_image: xcode10
      nodejs: "8"
    - osx_image: xcode10
      nodejs: "10"
script:
  - npm install
